name: Build Installers and Upload Artifacts

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build installer
        run: ${{ matrix.os == 'windows-latest' && 'gradlew.bat jlink' || './gradlew jlink' }}
        shell: ${{ matrix.os == 'windows-latest' && 'cmd' || 'bash' }}

      - name: List build files
        run: ls -lR build || echo "No build folder"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-installer
          path: build/image/**
