name: Build Installers

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Windows installer with jlink
        run: ./gradlew.bat jlink

      - name: List build folder contents (Windows)
        run: dir build /s

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: build/image/Clicker-setup.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build macOS installer with jlink
        run: ./gradlew jlink

      - name: List build folder contents (macOS)
        run: ls -lR build

      - name: Upload macOS installer
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: build/image/Clicker-1.0.dmg
