name: Build and Release Installers

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission to Gradle
        run: git update-index --chmod=+x gradlew

      - name: Build Windows EXE
        run: .\gradlew.bat jlink

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/image/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS Installer
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build macOS DMG
        run: ./gradlew jlink

      - name: Upload DMG to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/image/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
